const works = [
  {
    id: 1,
    title: 'Portfolio Website',
    postType: 'Featured',
    categories: 'Next js Tailewind CSS Express Js MongoDB TypeScript',
    info: 'Personal Website V1 Second iteration of my personal website. Designed and developed with a conscious effort to avoid Personal Website V1 Second iteration of my personal website.',
    link: '#',
    image: '/./work-project.jpg',
  },
  {
    id: 2,
    title: 'Portfolio Website',
    postType: 'Awesome',
    categories: 'Next js Tailewind CSS Express Js MongoDB TypeScript',
    info: 'Personal Website V2 Second iteration of my personal website. Designed and developed with a conscious effort to avoid Personal Website V1 Second iteration of my personal website.',
    link: '#',
    image: '/./work-project.jpg',
  },
  {
    id: 3,
    title: 'Portfolio Website',
    postType: 'Featured',
    categories: 'Next js Tailewind CSS Express Js MongoDB TypeScript',
    info: 'Personal Website V2 Second iteration of my personal website. Designed and developed with a conscious effort to avoid Personal Website V1 Second iteration of my personal website.',
    link: '#',
    image: '/./work-project.jpg',
  },
  {
    id: 4,
    title: 'Portfolio Website',
    postType: 'Featured',
    categories: 'Next js Tailewind CSS Express Js MongoDB TypeScript',
    info: 'Personal Website V2 Second iteration of my personal website. Designed and developed with a conscious effort to avoid Personal Website V1 Second iteration of my personal website.',
    link: '#',
    image: '/./work-project.jpg',
  },
  {
    id: 5,
    title: 'Portfolio Website',
    postType: 'Featured',
    categories: 'Next js Tailewind CSS Express Js MongoDB TypeScript',
    info: 'Personal Website V2 Second iteration of my personal website. Designed and developed with a conscious effort to avoid Personal Website V1 Second iteration of my personal website.',
    link: '#',
    image: '/./work-project.jpg',
  },
  {
    id: 6,
    title: 'Portfolio Website',
    postType: 'Featured',
    categories: 'Next js Tailewind CSS Express Js MongoDB TypeScript',
    info: 'Personal Website V2 Second iteration of my personal website. Designed and developed with a conscious effort to avoid Personal Website V1 Second iteration of my personal website.',
    link: '#',
    image: '/./work-project.jpg',
  },
];

export default works;
